import type { PecaCandidata } from "@/lib/pecas/tipos";

// Peças candidatas-semente do MVP, derivadas dos sinais (Descobrir). Os 4 fatores
// são dados de demonstração — moram no seed, nunca dentro do componente.
export const PECAS_SEMENTE: PecaCandidata[] = [
  {
    id: "saia-midi-plissada",
    titulo: "Saia midi plissada",
    categoria: "Saias",
    nichos: ["feminino", "plus"],
    loteMinimo: 12,
    precoAtacado: 55,
    origemSinalId: "saia-midi-plissada",
    fatores: {
      engajamentoRedes: 85,
      crescimentoBusca: 80,
      aderenciaPublico: 78,
      saturacao: 30,
    },
  },
  {
    id: "calca-alfaiataria-fluida",
    titulo: "Calça de alfaiataria fluida",
    categoria: "Alfaiataria",
    nichos: ["feminino", "masculino", "plus"],
    loteMinimo: 10,
    precoAtacado: 79,
    origemSinalId: "calca-alfaiataria-fluida",
    fatores: {
      engajamentoRedes: 70,
      crescimentoBusca: 76,
      aderenciaPublico: 82,
      saturacao: 35,
    },
  },
  {
    id: "vestido-chemise",
    titulo: "Vestido chemise",
    categoria: "Vestidos",
    nichos: ["feminino", "plus"],
    loteMinimo: 8,
    precoAtacado: 69,
    origemSinalId: "vestido-chemise",
    fatores: {
      engajamentoRedes: 66,
      crescimentoBusca: 64,
      aderenciaPublico: 72,
      saturacao: 40,
    },
  },
  {
    id: "conjunto-fitness-canelado",
    titulo: "Conjunto fitness canelado",
    categoria: "Activewear",
    nichos: ["fitness", "feminino"],
    loteMinimo: 15,
    precoAtacado: 64,
    origemSinalId: "conjunto-fitness-canelado",
    fatores: {
      engajamentoRedes: 78,
      crescimentoBusca: 71,
      aderenciaPublico: 60,
      saturacao: 45,
    },
  },
  {
    id: "jaqueta-jeans-oversized",
    titulo: "Jaqueta jeans oversized",
    categoria: "Jeanswear",
    nichos: ["feminino", "masculino", "plus"],
    loteMinimo: 6,
    precoAtacado: 89,
    origemSinalId: "jaqueta-jeans-oversized",
    fatores: {
      engajamentoRedes: 72,
      crescimentoBusca: 73,
      aderenciaPublico: 68,
      saturacao: 38,
    },
  },
  {
    id: "tricot-canelado",
    titulo: "Tricot canelado leve",
    categoria: "Malharia",
    nichos: ["feminino", "masculino"],
    loteMinimo: 12,
    precoAtacado: 52,
    origemSinalId: "tricot-canelado",
    fatores: {
      engajamentoRedes: 55,
      crescimentoBusca: 58,
      aderenciaPublico: 70,
      saturacao: 50,
    },
  },
  {
    id: "biquini-cortininha",
    titulo: "Biquíni cortininha",
    categoria: "Beachwear",
    nichos: ["praia", "feminino"],
    loteMinimo: 20,
    precoAtacado: 39,
    origemSinalId: "biquini-cortininha",
    fatores: {
      engajamentoRedes: 50,
      crescimentoBusca: 42,
      aderenciaPublico: 48,
      saturacao: 72, // já saturada — o motor deve segurar a quantidade
    },
  },
  {
    id: "colete-alfaiataria",
    titulo: "Colete de alfaiataria",
    categoria: "Alfaiataria",
    nichos: ["feminino"],
    loteMinimo: 10,
    precoAtacado: 59,
    origemSinalId: "colete-alfaiataria",
    fatores: {
      engajamentoRedes: 44,
      crescimentoBusca: 40,
      aderenciaPublico: 52,
      saturacao: 68,
    },
  },

  // --- Lote ampliado de catálogo (demonstração) — mais SKUs por nicho ---
  {
    id: "vestido-longo-festa",
    titulo: "Vestido longo de festa",
    categoria: "Vestidos",
    nichos: ["feminino", "plus"],
    loteMinimo: 8,
    precoAtacado: 95,
    fatores: {
      engajamentoRedes: 74,
      crescimentoBusca: 70,
      aderenciaPublico: 76,
      saturacao: 33,
    },
  },
  {
    id: "vestido-floral-curto",
    titulo: "Vestido floral curto",
    categoria: "Vestidos",
    nichos: ["feminino"],
    loteMinimo: 10,
    precoAtacado: 72,
    fatores: {
      engajamentoRedes: 81,
      crescimentoBusca: 77,
      aderenciaPublico: 79,
      saturacao: 28,
    },
  },
  {
    id: "vestido-envelope-floral",
    titulo: "Vestido envelope floral",
    categoria: "Vestidos",
    nichos: ["feminino", "praia"],
    loteMinimo: 8,
    precoAtacado: 85,
    fatores: {
      engajamentoRedes: 68,
      crescimentoBusca: 72,
      aderenciaPublico: 74,
      saturacao: 36,
    },
  },
  {
    id: "moletom-oversized",
    titulo: "Moletom oversized",
    categoria: "Streetwear",
    nichos: ["feminino", "masculino"],
    loteMinimo: 12,
    precoAtacado: 68,
    fatores: {
      engajamentoRedes: 88,
      crescimentoBusca: 84,
      aderenciaPublico: 80,
      saturacao: 25,
    },
  },
  {
    id: "top-fitness-sustentacao",
    titulo: "Top fitness alta sustentação",
    categoria: "Activewear",
    nichos: ["fitness", "feminino"],
    loteMinimo: 15,
    precoAtacado: 48,
    fatores: {
      engajamentoRedes: 79,
      crescimentoBusca: 75,
      aderenciaPublico: 66,
      saturacao: 42,
    },
  },
  {
    id: "short-jeans-destroyed",
    titulo: "Short jeans destroyed",
    categoria: "Jeanswear",
    nichos: ["feminino"],
    loteMinimo: 12,
    precoAtacado: 49,
    fatores: {
      engajamentoRedes: 64,
      crescimentoBusca: 60,
      aderenciaPublico: 62,
      saturacao: 55,
    },
  },
  {
    id: "camiseta-pima-masculina",
    titulo: "Camiseta pima masculina",
    categoria: "Camisaria",
    nichos: ["masculino"],
    loteMinimo: 10,
    precoAtacado: 44,
    fatores: {
      engajamentoRedes: 58,
      crescimentoBusca: 55,
      aderenciaPublico: 70,
      saturacao: 48,
    },
  },
  {
    id: "camisa-social-listrada",
    titulo: "Camisa social listrada",
    categoria: "Camisaria",
    nichos: ["masculino"],
    loteMinimo: 10,
    precoAtacado: 75,
    fatores: {
      engajamentoRedes: 47,
      crescimentoBusca: 44,
      aderenciaPublico: 58,
      saturacao: 60,
    },
  },
  {
    id: "saia-gode-midi",
    titulo: "Saia godê midi",
    categoria: "Saias",
    nichos: ["feminino", "plus"],
    loteMinimo: 10,
    precoAtacado: 62,
    fatores: {
      engajamentoRedes: 72,
      crescimentoBusca: 74,
      aderenciaPublico: 71,
      saturacao: 34,
    },
  },
  {
    id: "calca-alfaiataria-masculina",
    titulo: "Calça de alfaiataria masculina",
    categoria: "Alfaiataria",
    nichos: ["masculino"],
    loteMinimo: 10,
    precoAtacado: 89,
    fatores: {
      engajamentoRedes: 55,
      crescimentoBusca: 62,
      aderenciaPublico: 64,
      saturacao: 45,
    },
  },
  {
    id: "camiseta-streetwear-estampada",
    titulo: "Camiseta streetwear estampada",
    categoria: "Streetwear",
    nichos: ["masculino"],
    loteMinimo: 12,
    precoAtacado: 45,
    fatores: {
      engajamentoRedes: 83,
      crescimentoBusca: 79,
      aderenciaPublico: 68,
      saturacao: 38,
    },
  },
  {
    id: "saia-plissada-acetinada",
    titulo: "Saia plissada acetinada",
    categoria: "Saias",
    nichos: ["feminino"],
    loteMinimo: 12,
    precoAtacado: 70,
    fatores: {
      engajamentoRedes: 70,
      crescimentoBusca: 66,
      aderenciaPublico: 73,
      saturacao: 40,
    },
  },
  {
    id: "jaqueta-couro-masculina",
    titulo: "Jaqueta de couro masculina",
    categoria: "Outerwear",
    nichos: ["masculino"],
    loteMinimo: 6,
    precoAtacado: 135,
    fatores: {
      engajamentoRedes: 60,
      crescimentoBusca: 58,
      aderenciaPublico: 55,
      saturacao: 50,
    },
  },
  {
    id: "cardigan-trancado",
    titulo: "Cardigã tricô trançado",
    categoria: "Malharia",
    nichos: ["feminino", "plus"],
    loteMinimo: 8,
    precoAtacado: 78,
    fatores: {
      engajamentoRedes: 52,
      crescimentoBusca: 56,
      aderenciaPublico: 68,
      saturacao: 52,
    },
  },
  {
    id: "calca-wide-leg-jeans",
    titulo: "Calça wide leg jeans",
    categoria: "Jeanswear",
    nichos: ["feminino", "plus"],
    loteMinimo: 8,
    precoAtacado: 92,
    fatores: {
      engajamentoRedes: 77,
      crescimentoBusca: 80,
      aderenciaPublico: 75,
      saturacao: 30,
    },
  },
  {
    id: "pantalona-fluida",
    titulo: "Pantalona fluida",
    categoria: "Alfaiataria",
    nichos: ["feminino", "plus"],
    loteMinimo: 10,
    precoAtacado: 82,
    fatores: {
      engajamentoRedes: 69,
      crescimentoBusca: 73,
      aderenciaPublico: 78,
      saturacao: 35,
    },
  },
  {
    id: "blazer-xadrez-alongado",
    titulo: "Blazer xadrez alongado",
    categoria: "Alfaiataria",
    nichos: ["feminino"],
    loteMinimo: 6,
    precoAtacado: 110,
    fatores: {
      engajamentoRedes: 66,
      crescimentoBusca: 64,
      aderenciaPublico: 70,
      saturacao: 44,
    },
  },
  {
    id: "cropped-estampado",
    titulo: "Cropped estampado",
    categoria: "Streetwear",
    nichos: ["feminino"],
    loteMinimo: 24,
    precoAtacado: 39,
    fatores: {
      engajamentoRedes: 84,
      crescimentoBusca: 78,
      aderenciaPublico: 72,
      saturacao: 36,
    },
  },
  {
    id: "conjunto-infantil-moletom",
    titulo: "Conjunto infantil de moletom",
    categoria: "Infantil",
    nichos: ["infantil"],
    loteMinimo: 12,
    precoAtacado: 58,
    fatores: {
      engajamentoRedes: 62,
      crescimentoBusca: 65,
      aderenciaPublico: 74,
      saturacao: 40,
    },
  },
  {
    id: "camisa-linho-masculina",
    titulo: "Camisa de linho masculina",
    categoria: "Camisaria",
    nichos: ["masculino"],
    loteMinimo: 12,
    precoAtacado: 72,
    fatores: {
      engajamentoRedes: 71,
      crescimentoBusca: 68,
      aderenciaPublico: 69,
      saturacao: 38,
    },
  },
];
