import type { Sinal } from "@/lib/sinais/tipos";

// Sinais-semente do MVP. Edição = editar este arquivo (dados de demonstração).
// Regra do projeto: número de tendência inventado mora no seed, nunca no componente.
export const SINAIS_SEMENTE: Sinal[] = [
  {
    id: "saia-midi-plissada",
    titulo: "Saia midi plissada",
    categoria: "Saias",
    forca: 82,
    direcao: "em-alta",
    fonte: "redes",
    contexto:
      "Buscas e salvamentos crescendo entre criadoras de moda no Sudeste; aparece em looks de transição de estação.",
    nichos: ["feminino", "plus"],
    horizonte: "janela de ~6 semanas",
  },
  {
    id: "calca-alfaiataria-fluida",
    titulo: "Calça de alfaiataria fluida",
    categoria: "Alfaiataria",
    forca: 76,
    direcao: "em-alta",
    fonte: "publico-loja",
    contexto:
      "Clientes da sua faixa de ticket experimentando mais peças de caimento solto nas últimas semanas.",
    nichos: ["feminino", "masculino", "plus"],
    horizonte: "janela de ~8 semanas",
  },
  {
    id: "tricot-canelado",
    titulo: "Tricot canelado leve",
    categoria: "Malharia",
    forca: 68,
    direcao: "estavel",
    fonte: "fornecedor",
    contexto:
      "Dois fornecedores bem pontuados reforçando a grade; giro consistente, sem pico — aposta de base.",
    nichos: ["feminino", "masculino"],
    horizonte: "janela de ~10 semanas",
  },
  {
    id: "vestido-chemise",
    titulo: "Vestido chemise",
    categoria: "Vestidos",
    forca: 64,
    direcao: "em-alta",
    fonte: "redes",
    contexto:
      "Formato versátil ganhando tração em conteúdos de 'looks de trabalho'; combina com sua curadoria.",
    nichos: ["feminino", "plus"],
    horizonte: "janela de ~5 semanas",
  },
  {
    id: "conjunto-fitness-canelado",
    titulo: "Conjunto fitness canelado",
    categoria: "Activewear",
    forca: 71,
    direcao: "em-alta",
    fonte: "redes",
    contexto:
      "Tecido canelado dominando vitrines de activewear; alta intenção de compra em público jovem.",
    nichos: ["fitness", "feminino"],
    horizonte: "janela de ~7 semanas",
  },
  {
    id: "camisa-linho-masculina",
    titulo: "Camisa de linho masculina",
    categoria: "Camisaria",
    forca: 58,
    direcao: "estavel",
    fonte: "fornecedor",
    contexto:
      "Demanda sazonal previsível; fornecedores com pronta-entrega e lote mínimo acessível.",
    nichos: ["masculino"],
    horizonte: "janela de ~9 semanas",
  },
  {
    id: "biquini-cortininha",
    titulo: "Biquíni cortininha",
    categoria: "Beachwear",
    forca: 49,
    direcao: "esfriando",
    fonte: "redes",
    contexto:
      "Pico de verão já passou; ainda vende, mas a curva de interesse está cedendo — cuidado com excesso.",
    nichos: ["praia", "feminino"],
    horizonte: "janela curta de ~3 semanas",
  },
  {
    id: "jaqueta-jeans-oversized",
    titulo: "Jaqueta jeans oversized",
    categoria: "Jeanswear",
    forca: 73,
    direcao: "em-alta",
    fonte: "publico-loja",
    contexto:
      "Reentrada sazonal: seu público recompra jeans estruturado quando a temperatura cai.",
    nichos: ["feminino", "masculino", "plus"],
    horizonte: "janela de ~6 semanas",
  },
  {
    id: "conjunto-infantil-moletom",
    titulo: "Conjunto infantil de moletom",
    categoria: "Infantil",
    forca: 61,
    direcao: "estavel",
    fonte: "fornecedor",
    contexto:
      "Básico de inverno com giro confiável; bom para diluir risco no mix da próxima compra.",
    nichos: ["infantil"],
    horizonte: "janela de ~12 semanas",
  },
  {
    id: "colete-alfaiataria",
    titulo: "Colete de alfaiataria",
    categoria: "Alfaiataria",
    forca: 44,
    direcao: "esfriando",
    fonte: "redes",
    contexto:
      "Sinal que foi forte e perde fôlego; entra só como complemento de look, não como aposta principal.",
    nichos: ["feminino"],
    horizonte: "janela curta de ~4 semanas",
  },

  // --- Feed ampliado de sinais (demonstração) — pareados com o catálogo ---
  {
    id: "vestido-floral-curto",
    titulo: "Vestido floral curto",
    categoria: "Vestidos",
    forca: 84,
    direcao: "em-alta",
    fonte: "redes",
    contexto:
      "Estampa floral disparando em conteúdos de primavera/verão; alto salvamento entre criadoras do seu público.",
    nichos: ["feminino"],
    horizonte: "janela de ~5 semanas",
  },
  {
    id: "moletom-oversized",
    titulo: "Moletom oversized",
    categoria: "Streetwear",
    forca: 88,
    direcao: "em-alta",
    fonte: "redes",
    contexto:
      "Caimento oversized lidera o streetwear de inverno; intenção de compra forte em público jovem unissex.",
    nichos: ["feminino", "masculino"],
    horizonte: "janela de ~7 semanas",
  },
  {
    id: "camiseta-streetwear-estampada",
    titulo: "Camiseta streetwear estampada",
    categoria: "Streetwear",
    forca: 82,
    direcao: "em-alta",
    fonte: "redes",
    contexto:
      "Estampas gráficas em alta nas vitrines masculinas; giro rápido e ticket de entrada acessível.",
    nichos: ["masculino"],
    horizonte: "janela de ~6 semanas",
  },
  {
    id: "cropped-estampado",
    titulo: "Cropped estampado",
    categoria: "Streetwear",
    forca: 81,
    direcao: "em-alta",
    fonte: "redes",
    contexto:
      "Cropped com estampa puxando o básico jovem; alto engajamento e lote mínimo diluído pelo preço baixo.",
    nichos: ["feminino"],
    horizonte: "janela de ~6 semanas",
  },
  {
    id: "calca-wide-leg-jeans",
    titulo: "Calça wide leg jeans",
    categoria: "Jeanswear",
    forca: 80,
    direcao: "em-alta",
    fonte: "publico-loja",
    contexto:
      "Clientes do seu ticket migrando do skinny para o wide leg; recompra de jeans estruturado em alta.",
    nichos: ["feminino", "plus"],
    horizonte: "janela de ~8 semanas",
  },
  {
    id: "top-fitness-sustentacao",
    titulo: "Top fitness alta sustentação",
    categoria: "Activewear",
    forca: 79,
    direcao: "em-alta",
    fonte: "redes",
    contexto:
      "Busca por sustentação real cresce no activewear feminino; público fitness paga mais por caimento.",
    nichos: ["fitness", "feminino"],
    horizonte: "janela de ~7 semanas",
  },
  {
    id: "vestido-longo-festa",
    titulo: "Vestido longo de festa",
    categoria: "Vestidos",
    forca: 75,
    direcao: "em-alta",
    fonte: "redes",
    contexto:
      "Temporada de formaturas e casamentos aquecendo a busca por vestidos longos; ticket alto, margem boa.",
    nichos: ["feminino", "plus"],
    horizonte: "janela de ~6 semanas",
  },
  {
    id: "saia-gode-midi",
    titulo: "Saia godê midi",
    categoria: "Saias",
    forca: 74,
    direcao: "em-alta",
    fonte: "redes",
    contexto:
      "Silhueta rodada ganhando força em looks de transição; combina com a curadoria que sua loja já vende.",
    nichos: ["feminino", "plus"],
    horizonte: "janela de ~6 semanas",
  },
  {
    id: "pantalona-fluida",
    titulo: "Pantalona fluida",
    categoria: "Alfaiataria",
    forca: 72,
    direcao: "em-alta",
    fonte: "publico-loja",
    contexto:
      "Alfaiataria de caimento solto puxando o conforto-elegante; experimentação subindo na sua faixa de público.",
    nichos: ["feminino", "plus"],
    horizonte: "janela de ~8 semanas",
  },
  {
    id: "vestido-envelope-floral",
    titulo: "Vestido envelope floral",
    categoria: "Vestidos",
    forca: 70,
    direcao: "em-alta",
    fonte: "publico-loja",
    contexto:
      "Modelagem envelope com floral funciona bem em corpos variados; bom sinal para público feminino e de praia.",
    nichos: ["feminino", "praia"],
    horizonte: "janela de ~5 semanas",
  },
  {
    id: "saia-plissada-acetinada",
    titulo: "Saia plissada acetinada",
    categoria: "Saias",
    forca: 68,
    direcao: "em-alta",
    fonte: "redes",
    contexto:
      "Acetinado com plissado aparecendo em looks de festa do dia a dia; sinal consistente, sem pico de moda passageira.",
    nichos: ["feminino"],
    horizonte: "janela de ~7 semanas",
  },
  {
    id: "blazer-xadrez-alongado",
    titulo: "Blazer xadrez alongado",
    categoria: "Alfaiataria",
    forca: 64,
    direcao: "estavel",
    fonte: "redes",
    contexto:
      "Xadrez clássico volta a cada inverno; giro previsível como peça de composição, não como aposta de pico.",
    nichos: ["feminino"],
    horizonte: "janela de ~9 semanas",
  },
  {
    id: "short-jeans-destroyed",
    titulo: "Short jeans destroyed",
    categoria: "Jeanswear",
    forca: 62,
    direcao: "estavel",
    fonte: "fornecedor",
    contexto:
      "Básico de verão com demanda recorrente; fornecedores com pronta-entrega e lote mínimo acessível.",
    nichos: ["feminino"],
    horizonte: "janela de ~8 semanas",
  },
  {
    id: "calca-alfaiataria-masculina",
    titulo: "Calça de alfaiataria masculina",
    categoria: "Alfaiataria",
    forca: 60,
    direcao: "estavel",
    fonte: "publico-loja",
    contexto:
      "Demanda estável por alfaiataria masculina de caimento confortável; recompra puxada por trabalho e eventos.",
    nichos: ["masculino"],
    horizonte: "janela de ~10 semanas",
  },
  {
    id: "jaqueta-couro-masculina",
    titulo: "Jaqueta de couro masculina",
    categoria: "Outerwear",
    forca: 58,
    direcao: "estavel",
    fonte: "fornecedor",
    contexto:
      "Peça de inverno com ticket alto e giro lento; entra como âncora de vitrine, em quantidade controlada.",
    nichos: ["masculino"],
    horizonte: "janela de ~12 semanas",
  },
  {
    id: "camiseta-pima-masculina",
    titulo: "Camiseta pima masculina",
    categoria: "Camisaria",
    forca: 56,
    direcao: "estavel",
    fonte: "fornecedor",
    contexto:
      "Básico premium de recompra alta; algodão pima sustenta margem melhor que a camiseta comum.",
    nichos: ["masculino"],
    horizonte: "janela de ~11 semanas",
  },
  {
    id: "cardigan-trancado",
    titulo: "Cardigã tricô trançado",
    categoria: "Malharia",
    forca: 54,
    direcao: "estavel",
    fonte: "fornecedor",
    contexto:
      "Tricô de tração começa a aparecer com a queda de temperatura; sinal de base para o mix de inverno.",
    nichos: ["feminino", "plus"],
    horizonte: "janela de ~10 semanas",
  },
  {
    id: "camisa-social-listrada",
    titulo: "Camisa social listrada",
    categoria: "Camisaria",
    forca: 46,
    direcao: "esfriando",
    fonte: "redes",
    contexto:
      "Social listrada perde espaço para o casual; mantém só como reposição de grade, não como aposta.",
    nichos: ["masculino"],
    horizonte: "janela curta de ~4 semanas",
  },
];
